### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by abbiekressner** [brglng/windows-console-color-solarized#1]
Thanks for your work on this! I would really love to get solarized on my Git Bash, Powershell, etc. Unfortunately, nothing seems to happen to the colorschemes when I apply the reg file. I get a notice that says that the settings have been applied successfully, but the colors are still the old default in Git Bash, Powershell, etc when I open these programs back up. Do you have any recommendations for getting this colorscheme on my computer?

**Comment by brglng** [comment]
Hi @abbiekressner , I think you can check if there are program-specific color settings under registry key HKCU\Console . I don't have Windows 10 to test currently, but I think there should be not much difference among Windows 7, 8, 8.1 and 10.

**Comment by abbiekressner** [comment]
I ended up getting the colors to change with this method actually: https://github.com/mavnn/mintty-colors-solarized

I don't know enough about Windows yet (I'm usually on Unix) to know how and why these two methods are different, but I have solarized where I want it so I'm happy. Thanks for your reply though! Cheers!
